### ISSUE TITLE
Link to line

### ISSUE THREAD

**Issue by Nebucatnetzer** [ryanjamurphy/review-obsidian#6]
Another idea would be to add an option to link to a specific line e.g. where the cursor currently is.
And then in the journal file use the `![[link]]` format to display the task directly in the file.
This would be very useful for getting back to people.
I could image two ways this could be implemented, either as an option in the settings which lets you enable it for the current review command.
Or as a new review command for example called "Review current line" or so.

```
Important project.md

# Tasks
- [ ] Wait for answer from Mike about the project status.
```

```
2020-11-17.md
![[Important project^lsd87d]]
```

**Comment by ryanjamurphy** [comment]
Aye! In fact, one of the reasons I developed the workbench plugin was to explore how to interact with block embeds and linking. I plan on adding "review this block" in the next update to this plugin.

Thanks!

**Comment by Nebucatnetzer** [comment]
I started to do this manually and noticed something that would be very useful.
When I look at a task like the following, I often want to know until when I gave X time to reply.
```
- [ ] Waiting for reply from X ^lsd87d
```
I solved this for the moment with a link from the task to the note.

```
Important project.md

# Tasks
- [ ] Waiting for reply from X [[2020-11-17]] ^lsd87d
```

```
2020-11-17.md
![[Important project^lsd87d]]
```
Maybe Review could do this automatically?

**Comment by ryanjamurphy** [comment]
So you just mean adding the date-note to the line when you hit "Review this block..."  do I have that right?

In that case, we're on the same page again. I am planning a "rich task management" plugin to offer this via a "schedule this task"-type functionality, along with some other mechanics (like cancelled tasks).

**Comment by Nebucatnetzer** [comment]
Yes exactly.
Nice I'm looking forward to it.
I was using Emacs Org-mode for a long time, which is great but there's just not enough support for it out there.

**Comment by ryanjamurphy** [comment]
Implemented "review this block" as a new command in 1.5.0. 

@Nebucatnetzer this doesn't include the addition of the date in the block-line like you've described [here](https://github.com/ryanjamurphy/review-obsidian/issues/6#issuecomment-726828776), just to be clear. I still intend on implementing that kind of task management in a different plugin.

**Comment by Nebucatnetzer** [comment]
No problem, this is already a big help, thank you!
